# Generated by Django 2.0 on 2018-12-03 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_expenses_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splittransactions',
            name='spentby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_spentby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='splittransactions',
            name='spentfor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_spentfor', to=settings.AUTH_USER_MODEL),
        ),
    ]
