# Generated by Django 2.0 on 2018-12-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181203_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='splittransactions',
            name='mode',
            field=models.CharField(default='S', max_length=1),
            preserve_default=False,
        ),
    ]
