# Generated by Django 2.0 on 2018-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181202_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='test',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
