# Generated by Django 2.0 on 2018-12-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expenses_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='test',
        ),
    ]
